version: "3.4"
services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"

  
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: hsdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root


volumes:
  db_data: {}
